version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data:
  prometheus: